### ISSUE TITLE
npm run dev fails

### ISSUE THREAD

**Issue by gamebusterz** [luosijie/vue-resume#4]
npm run dev fails with the following error. I have nodejs and npm installed on my system.

```
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::8080
    at Object.exports._errnoException (util.js:1020:11)
    at exports._exceptionWithHostPort (util.js:1043:20)
    at Server._listen2 (net.js:1258:14)
    at listen (net.js:1294:10)
    at Server.listen (net.js:1390:5)
    at EventEmitter.listen (/home/yankee/vue-resume/node_modules/express/lib/application.js:618:24)
    at Object.<anonymous> (/home/yankee/vue-resume/build/dev-server.js:83:18)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:504:3
```

**Comment by luosijie** [comment]
Did you took the right steps
```
git clone "https://github.com/luosijie/vue-resume"
```
```
cd vue-resume/
```
```
npm install
```
```
npm run dev
```

It's working on my computer

**Comment by gamebusterz** [comment]
Yes, I forked the repo and then repeated the same steps.  `npm install` completed without any errors.
Nodejs version: v6.11.2
npm version: npm: '3.10.10'

**Comment by luosijie** [comment]
Try turning off all **Node.js process** in the **task manager**
before 
```
npm run dev
```

**Comment by riyaz-ali** [comment]
_EADDRINUSE_ in use suggests that the port 8080 is already in use. If you are on a linux system use `netstat -tlp | grep 8080` to get the PID of the program and then send kill signal `kill 9 <PID>`

**Comment by gamebusterz** [comment]
@riyaz-ali Thanks, that works.
